; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\maya1\AppData\Local\Temp\.NETFramework,Version=v4.7.1.AssemblyAttributes.cpp"
